config/routes.rb
Rails.application.routes.draw do
  resources :tapes
  resources :bands
	root 'static_pages#home'
  match '/sets',    to: 'static_pages#sets',    via: 'get'
  match '/black',    to: 'static_pages#black',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/models/tape.rb
class Tape < ActiveRecord::Base
	default_scope -> { order('tp_date DESC') }
  validates :tp_article, presence: true
	validates :tp_url, presence: true, uniqueness: true
end

app/controllers/tapes_controller.rb
class TapesController < ApplicationController
  before_action :set_tape, only: [:show, :edit, :update, :destroy]

  # GET /tapes
  # GET /tapes.json
  def index
    @tapes = Tape.all
  end

  # GET /tapes/1
  # GET /tapes/1.json
  def show
  end

  # GET /tapes/new
  def new
#    @tape = Tape.new
    @agent = Mechanize.new
    my_site = 1   # "Економична правда"
    my_url = 'https://www.epravda.com.ua'
    my_section = [
      '/tags/bitcoin/', 
      '/tags/59a7b3ae95270/', 
      '/tags/59b0191ec5009/', 
      '/news/', 
      '/tags/finansi/', 
      '/tags/it-tekhnologiji/'
      ]
    my_section.each do |sec|
      rss_new(my_url, sec, my_site)
    end

    # https://www.bloomberg.com/crypto
    my_site = 2   # "Bloomberg"
    my_url = 'https://www.bloomberg.com'
    my_section = [
      '/crypto'
      ]
    my_section.each do |sec|
      rss_new(my_url, sec, my_site)
    end

    # https://www.bloomberg.com/crypto
    my_site = 3   # "Сегодня"
    my_url = 'https://www.segodnya.ua'
    my_section = [
      '/economics.html'
      ]
    my_section.each do |sec|
      rss_seg(my_url, sec, my_site)
    end

    redirect_to tapes_path	#tapes#index
   
  end #new

  # GET /tapes/1/edit
  def edit
    #render :edit
    #redirect_to tapes_path	#
  end

  # POST /tapes
  # POST /tapes.json
  def create
    @tape = Tape.new(tape_params)

    respond_to do |format|
      if @tape.save
        format.html { redirect_to @tape, notice: 'Tape was successfully created.' }
        format.json { render :show, status: :created, location: @tape }
      else
        format.html { render :new }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end #if
    end   #do
  end     #def

  # PATCH/PUT /tapes/1
  # PATCH/PUT /tapes/1.json
  def update
    respond_to do |format|
      if @tape.update(tape_params)
        format.html { redirect_to @tape, notice: 'Tape was successfully updated.' }
        format.json { render :show, status: :ok, location: @tape }
      else
        format.html { render :edit }
        format.json { render json: @tape.errors, status: :unprocessable_entity }
      end #if
    end   #do
  end     #def

  # DELETE /tapes/1
  # DELETE /tapes/1.json
  def destroy
    @tape.destroy
    respond_to do |format|
      format.html { redirect_to tapes_url, notice: 'Tape was successfully destroyed.' }
      format.json { head :no_content }
    end #do
  end   #def

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tape
      @tape = Tape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tape_params
      params.require(:tape).permit(:tp_site, :tp_date, :tp_article, :tp_url, :tp_status, :tp_tag, :tp_comments)
    end
    
    def rss_new(my_url, my_section, my_site)   #serch links site
    page = @agent.get(my_url + my_section)
    isx_status = 0
    #links_site = page.links_with(text: /(крипто)|(біткоїн)|(фінтех)|(блокчейн)|(Bitcoin)|(платіжн.+систем)/)
#    links_site = page.links_with(text: /itcoin/)
    all_links = page.links()
# byebug
      all_links.each do |art|
        need_art = need_tag(art, my_site)
        
        if need_art == true
          if my_site == 1 
            d1 = /20\d\d\/\d\d\/\d+/.match(art.href)            
            comments_tape = d1.to_s
            date_tape = Date.parse(d1.to_s)
            url_tape = my_url + art.href()
            head_tape = art.text()
          elsif my_site == 2
            d1 = /20\d\d-\d\d-\d+/.match(art.href)
            comments_tape = d1.to_s
#            byebug
            date_tape = Date.parse(d1.to_s)
            url_tape = my_url + art.href()
            head_tape = art.text()
          end #if my_site == 1 
  #        byebug
          tape = Tape.new(tp_site: my_site, 
                          tp_status: isx_status, 
                          tp_url: url_tape, 
                          tp_article: head_tape, 
                          tp_tag: @tag_art, 
                          tp_date: date_tape, 
                          tp_comments: comments_tape)
          tape.save
        end   #if need_art == true      
#        byebug
      end # each
    end #def rss_new
    
    def rss_seg(my_url, my_section, my_site)   #serch links site
    page = @agent.get(my_url + my_section)
    isx_status = 0
    link_krypto = page.link_with(text: /Криптовалюта/, href: /kriptovalyuta/)
    page = link_krypto.click
    all_links = page.links()
    doc = Nokogiri::HTML(page.body)                           # читаю в Nokogiri ...
    div_block_article = doc.css("div[class=content-blocks]")  # ... и выбираю весь блок;
    all_links = div_block_article.css("a")
      all_links.each do |art|
        need_art = need_tag(art, my_site)
        if need_art == true
          if my_site == 1 
            d1 = /20\d\d\/\d\d\/\d+/.match(art.href)
            date_tape = Date.parse(d1.to_s)
            url_tape = my_url + art.href()
          elsif my_site == 2
            d1 = /20\d\d-\d\d-\d+/.match(art.href)
#            byebug
            date_tape = Date.parse(d1.to_s)
            url_tape = art.href()
          elsif my_site == 3
            my_href = art["href"]
            head_tape = art.css("h3").text()
            d2 = art.css("span[class=date]").text()
            d1 = date_rus(d2)
            date_tape = DateTime.parse(d1)
            comments_tape = d1.to_s
            url_tape = my_url + my_href
   	        if art["href"] =~ /fintech/
	            @tag_art = 'FinTech'
	          elsif art["href"] =~ /blockchain/
	            @tag_art = 'blockChain'
	          elsif art["href"] =~ /bitcoin/  #bitkoina
	            @tag_art = 'bitcoin'
	          elsif art["href"] =~ /bitkoin/  
	            @tag_art = 'bitcoin'
	          elsif art["href"] =~ /crypto/
	            @tag_art = 'krypto'
	          else
	          end   #if art["href"] =~ /fintech/
          end        #my_site == 1
#         byebug
          tape = Tape.new(tp_site: my_site, 
                          tp_status: isx_status, 
                          tp_url: url_tape, 
                          tp_article: head_tape, 
                          tp_tag: @tag_art, 
                          tp_date: date_tape, 
                          tp_comments: comments_tape)
          tape.save
        end   #if need_art == true      
#        byebug
      end # each
    end #def rss_seg

    def need_tag(art, my_site)
      need_art = false
      @tag_art = " "
      if my_site == 1 #"Економ.правда"
	      if art.text() =~ /(Б|б)іткоїн/
	        need_art = true
	        @tag_art = 'bitcoin'
	      elsif art.text() =~ /(B|b)itcoin/
	        need_art = true
	        @tag_art = 'bitcoin'
	      elsif art.text() =~ /(К|к)рипто/
	        need_art = true
	        @tag_art = 'krypto'
	      elsif art.text() =~ /(Ф|ф)ін(Т|т)ех/
	        need_art = true
	        @tag_art = 'FinTech'
	      elsif art.text() =~ /(Б|б)локчейн/
	        need_art = true
	        @tag_art = 'blockChain'
	      elsif art.text() =~ /(П|п)латіжн.+систем/
	        need_art = true
	        @tag_art = 'PaySys'
	      else
	      end   #if art.text() =~ /(Б|біткоїн)/
	    elsif my_site == 2  # Bloomberg
	      if art.href() =~ /articles/
          need_art = true
	        if art.href() =~ /bitcoin/
	          @tag_art = 'bitcoin'
	        elsif art.href() =~ /fintech/
	          @tag_art = 'FinTech'
	        elsif art.href() =~ /blockchain/
	          @tag_art = 'blockChain'
	        elsif art.href() =~ /crypto/
	          @tag_art = 'krypto'
	        else
	        end   #if art.href() =~ /bitcoin/
	      else
	        need_art = false
	      end #art.href() =~ /articles/
	    elsif my_site == 3  # "Сегодня"
          need_art = true
	    end   # my_site == 3  # "Сегодня"
	    return need_art
    end #def
    
    def date_rus(d2)
      if d2 =~ /Сегодня/
        d2.gsub!(/Сегодня/, Date.today.to_s)
      elsif d2 =~ /Вчера/
        yestoday = Date.today - 86400
        d2.gsub!(/Вчера/, yestoday.to_s)
      elsif d2 =~ /(М|м)арта/
        d2.gsub!(/(М|м)арта/, 'MAR')
      elsif d2 =~ /(А|а)преля/
        d2.gsub!(/(А|а)преля/, 'APR')
      elsif d2 =~ /(М|м)ая/
        d2.gsub!(/(М|м)ая/, 'MAY')
      elsif d2 =~ /(И|и)юня/
        d2.gsub!(/(И|и)юня/, 'JUN')
      end  # if d2 =~ /Сегодня/
      return d2
    end #    def date_rus(d2)

end

app/helpers/tapes_helper.rb
module TapesHelper
end

app/views/tapes/0_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tapes</h1>

<table>
  <thead>
    <tr>
      <th>Tp site</th>
      <th>Tp date</th>
      <th>Tp article</th>
      <th>Tp url</th>
      <th>Tp status</th>
      <th>Tp tag</th>
      <th>Tp comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tapes.each do |tape| %>
      <tr>
        <td><%= tape.tp_site %></td>
        <td><%= tape.tp_date %></td>
        <td><%= tape.tp_article %></td>
        <td><%= tape.tp_url %></td>
        <td><%= tape.tp_status %></td>
        <td><%= tape.tp_tag %></td>
        <td><%= tape.tp_comments %></td>
        <td><%= link_to 'Show', tape %></td>
        <td><%= link_to 'Edit', edit_tape_path(tape) %></td>
        <td><%= link_to 'Destroy', tape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tape', new_tape_path %>

app/views/tapes/1_index.html.erb
<h1>Полный список</h1>

<div class="row">
  <div class="span10">
    <%#= will_paginate %>
  </div>
</div>
<% @tapes.each do |fact| %>
  <div class="row">
    <div class="span1">
      <%= fact.tp_site %>
    </div>
    <div class="span1">
      <%= fact.tp_status %>
    </div>
    <div class="span1">
      <%= fact.tp_tag %>
    </div>
    <div class="span4">
      <%= fact.tp_article %>
    </div>
    <div class="span4">
      <%= fact.tp_comments %>
    </div>
    <div class="span1">
      <%#= link_to 'Show', tape %>
      <%= link_to 'Edit', edit_tape_path(fact) %>
      <%#= link_to 'Destroy', fact, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>


<% end %>
  <div class="span10">
    <%#= will_paginate %>
  </div>
</div>
<table>
  <thead>
    <tr>
      <th>Tp site</th>
      <th>Tp date</th>
      <th>Tp article</th>
      <th>Tp url</th>
      <th>Tp status</th>
      <th>Tp tag</th>
      <th>Tp comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tapes.each do |tape| %>
      <tr>
        <td><%= tape.tp_site %></td>
        <td><%= tape.tp_date %></td>
        <td><%= tape.tp_article %></td>
        <td><%= tape.tp_url %></td>
        <td><%= tape.tp_status %></td>
        <td><%= tape.tp_tag %></td>
        <td><%= tape.tp_comments %></td>
        <td><%= link_to 'Show', tape %></td>
        <td><%= link_to 'Edit', edit_tape_path(tape) %></td>
        <td><%= link_to 'Destroy', tape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tape', new_tape_path %>

app/views/tapes/1edit.html.erb
<h1>Editing Tape</h1>

<%= render 'form' %>

<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/2_ndex.html.erb
<h3>Полный список</h3>
<div class="container">
  <div class="row">
      <%#= will_paginate %>
  </div>

  <div class="row">
    <div class="col-md-1">Сайт</div>
    <div class="col-md-1">Статус</div>
    <div class="col-md-1">Тэг</div>
    <div class="col-md-4">Статья</div>
    <div class="col-md-4">Комментарии</div>
    <div class="col-md-1">Кнопки</div>
  </div>

  <% @tapes.each do |fact| %>
    <div class="row">
      <div class="col-md-1">
        <%= fact.tp_site %>
      </div>
      <div class="col-md-1">
        <%= fact.tp_status %>
      </div>
      <div class="col-md-1">
        <%= fact.tp_tag %>
      </div>
      <div class="col-md-4">
        <%= fact.tp_article %>
      </div>
      <div class="col-md-4">
        <%= fact.tp_comments %>
      </div>
      <div class="col-md-1">
        <%#= link_to 'Show', tape %>
        <%= link_to 'Edit', edit_tape_path(fact) %>
        <%#= link_to 'Destroy', fact, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>  <!--row-->
  <%end%>
  <div class="row">
    <%#= will_paginate %>
  </div>
</div>  !--container-->

app/views/tapes/2edit.html.erb
<h1>Editing Article</h1>

<div class="container">
<%= form_for(@tape) do |f| %>
  <% if @tape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tape.errors.count, "error") %> prohibited this tape from being saved:</h2>

      <ul>
      <% @tape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      Сайт: 
        <%= f.number_field :tp_site, size: 5 %>
      Тэг: 
        <%= f.text_field :tp_tag, size: 10 %>
      Статус: 
        <%= f.number_field :tp_status %>
  </div>
<div class="row"><div class="col-md-2">- </div> </div>

  <div class="row">
    <div class="col-md-2">Статья:</div>
    <div class="col-md-10">
      <%#= f.text_field :tp_article, size: 100 %>
      <%#= @tape.tp_article %>
   	  <%= link_to @tape.tp_article, @tape.tp_url %>   
    </div>
  </div>
<div class="row"><div class="col-md-2">- </div> </div>


  <div class="row">
    <div class="col-md-2">дата публикации:</div>
    <div class="col-md-10">
      <%= f.datetime_select :tp_date %>
    </div>
  </div>
<div class="row"><div class="col-md-2">- </div> </div>


  <div class="row">
    <div class="col-md-2">URL:</div>
    <div class="col-md-10">
      <%#= f.text_field :tp_url, size: 100 %>
      <%#=  @tape.tp_url %>
   	  <%= link_to @tape.tp_url, @tape.tp_url %>   
    </div>
<div class="row"><div class="col-md-2">- </div> </div>


  <div class="row">
    <div class="col-md-2">Коммент:</div>
    <div class="col-md-10">
      <%= f.text_area :tp_comments, cols: 100, rows: 7 %>
    </div>
  </div>
<div class="row"><div class="col-md-2">- </div> </div>


  <div class="row">
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>


<% end %>
</div>

<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/_form.html.erb
<%= form_for(@tape) do |f| %>
  <% if @tape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tape.errors.count, "error") %> prohibited this tape from being saved:</h2>

      <ul>
      <% @tape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tp_site %><br>
    <%= f.number_field :tp_site %>
  </div>
  <div class="field">
    <%= f.label :tp_date %><br>
    <%= f.datetime_select :tp_date %>
  </div>
  <div class="field">
    <%= f.label :tp_article %><br>
    <%= f.text_field :tp_article %>
  </div>
  <div class="field">
    <%= f.label :tp_url %><br>
    <%= f.text_field :tp_url %>
  </div>
  <div class="field">
    <%= f.label :tp_status %><br>
    <%= f.number_field :tp_status %>
  </div>
  <div class="field">
    <%= f.label :tp_tag %><br>
    <%= f.text_field :tp_tag %>
  </div>
  <div class="field">
    <%= f.label :tp_comments %><br>
    <%= f.text_field :tp_comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tapes/edit.html.erb
<h1>Editing Article</h1>

<div class="container">
<%= form_for(@tape) do |f| %>
  <% if @tape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tape.errors.count, "error") %> prohibited this tape from being saved:</h2>

      <ul>
      <% @tape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <p><strong>Сайт: </strong>
        <%= f.number_field :tp_site, size: 5 %>
      <strong>Тэг: </strong>
        <%= f.text_field :tp_tag, size: 10 %>
      <strong>Статус: </strong>
        <%= f.number_field :tp_status %>
      </p>
  </div>

  <div class="row">
    <div class="col-md-2">Статья:</div>
    <div class="col-md-10">
      <%#= f.text_field :tp_article, size: 100 %>
      <%#= @tape.tp_article %>
   	  <%= link_to @tape.tp_article, @tape.tp_url %>   
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">URL:</div>
    <div class="col-md-10">
      <%#= f.text_field :tp_url, size: 100 %>
      <%#=  @tape.tp_url %>
   	  <%= link_to @tape.tp_url, @tape.tp_url %>   
    </div>

  <div class="row">
    <div class="col-md-2">Коммент:</div>
    <div class="col-md-10">
      <%= f.text_area :tp_comments, cols: 100, rows: 7 %>
    </div>
  </div>

  <div class="row">
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>


<% end %>
</div>

<%= link_to 'Show', @tape %> |
<%= link_to 'Back', tapes_path %>

app/views/tapes/index.html.erb
<h3>Полный список</h3>
<div class="container">
  <div class="row">
      <%#= will_paginate %>
  </div>

  <div class="row">
    <div class="col-md-1">Сайт-Статус</div>
    <div class="col-md-1">Тэг</div>
    <div class="col-md-5">Статья</div>
    <div class="col-md-4">Комментарии</div>
    <div class="col-md-1">Кнопки</div>
  </div>

  <% @tapes.each do |fact| %>
    <div class="row">
      <div class="col-md-1">
        <%#= fact.tp_site.to_s + "-" + fact.tp_status.to_s + "-" + fact.tp_tag %>
        <%= fact.tp_site.to_s + "-" + fact.tp_status.to_s %>
      </div>
      <div class="col-md-1">
        <%= fact.tp_tag %>
      </div>
      <div class="col-md-4">
        <%#= fact.tp_article %>
     	  <%= link_to fact.tp_article, fact.tp_url %>   
      </div>
      <div class="col-md-5">
        <%= fact.tp_comments %>
      </div>
      <div class="col-md-1">
        <%#= link_to 'Show', tape %>
        <%= link_to 'Edit', edit_tape_path(fact) %>
        <%#= link_to 'Destroy', fact, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>  <!--row-->
  <%end%>
  <div class="row">
    <%#= will_paginate %>
  </div>
</div>  <!--container-->

app/views/tapes/new.html.erb
<h1>New Tape</h1>

<%= render 'form' %>

<%= link_to 'Back', tapes_path %>

app/views/tapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tp site:</strong>
  <%= @tape.tp_site %>
</p>

<p>
  <strong>Tp date:</strong>
  <%= @tape.tp_date %>
</p>

<p>
  <strong>Tp article:</strong>
  <%= @tape.tp_article %>
</p>

<p>
  <strong>Tp url:</strong>
  <%= @tape.tp_url %>
</p>

<p>
  <strong>Tp status:</strong>
  <%= @tape.tp_status %>
</p>

<p>
  <strong>Tp tag:</strong>
  <%= @tape.tp_tag %>
</p>

<p>
  <strong>Tp comments:</strong>
  <%= @tape.tp_comments %>
</p>

<%= link_to 'Edit', edit_tape_path(@tape) %> |
<%= link_to 'Back', tapes_path %>