config/routes.rb
Rails.application.routes.draw do
  resources :tapes
  resources :bands
	root 'static_pages#home'
  match '/sets',    to: 'static_pages#sets',    via: 'get'
  match '/black',    to: 'static_pages#black',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/models/band.rb
class Band < ActiveRecord::Base

	validates :bn_url, presence: true, uniqueness: true

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    agent = Mechanize.new
    str_search = "фондовые биржи"
    num_search = 1
    num_page = 1
    page = agent.get('http://google.com/')
    google_form = page.form('f')
    google_form.q = str_search
    google_form.ie = 'windows-1251'
    page = agent.submit(google_form)
    num_page = rss_new(page, num_search, num_page)
    link_next = page.links.find { |l| l.text =~ /Уперед/ }
    for i in [1..10] do
      break if link_next == nil
      page = link_next.click
      num_page = rss_new(page, num_search, num_page)
      link_next = page.links.find { |l| l.text =~ /Уперед/ }
#      i += 1
    end  
    redirect_to bands_path	#bands#index
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:bn_head, :bn_url, :bn_anonce, :bn_tema, :bn_rang, :bn_coment)
    end
    
    def rss_new(page, tema, num_page)   #skrab(words)
      doc = Nokogiri::HTML(page.body)
      div_cite = doc.css("cite")
      div_text = []
      div_cite.each do |cite|
        div_text.push(cite.text.strip)
      end
      div_uri = []
      div_text.each do |uri|
#        byebug if num_page>1
        if uri.class == String
          unless uri !~ /\A(https?:\/\/)*[^\/]+\//    #/\A[^\/]+\//
            id_name = /\A(https?:\/\/)*[^\/]+\//.match(uri)    #/\A[^\/]+\//.match(uri)
          else
            id_name = uri
          end
          div_uri.push(id_name.to_s)
        end #if uri.class == String
#        byebug      
      end
      div_uri.each do |rec|
        band = Band.new(bn_url: rec, bn_tema: tema)
        band.save
      end
#           byebug
      return num_page += 1
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bn_head %><br>
    <%= f.text_field :bn_head %>
  </div>
  <div class="field">
    <%= f.label :bn_url %><br>
    <%= f.text_field :bn_url %>
  </div>
  <div class="field">
    <%= f.label :bn_anonce %><br>
    <%= f.text_field :bn_anonce %>
  </div>
  <div class="field">
    <%= f.label :bn_tema %><br>
    <%= f.text_field :bn_tema %>
  </div>
  <div class="field">
    <%= f.label :bn_rang %><br>
    <%= f.number_field :bn_rang %>
  </div>
  <div class="field">
    <%= f.label :bn_coment %><br>
    <%= f.text_field :bn_coment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<h1>Editing Band</h1>

<%= render 'form' %>

<%= link_to 'Show', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bands</h1>

<table>
  <thead>
    <tr>
      <th>Bn head</th>
      <th>Bn url</th>
      <th>Bn anonce</th>
      <th>Bn tema</th>
      <th>Bn rang</th>
      <th>Bn coment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bands.each do |band| %>
      <tr>
        <td><%= band.bn_head %></td>
        <td><%= band.bn_url %></td>
        <td><%= band.bn_anonce %></td>
        <td><%= band.bn_tema %></td>
        <td><%= band.bn_rang %></td>
        <td><%= band.bn_coment %></td>
        <td><%= link_to 'Show', band %></td>
        <td><%= link_to 'Edit', edit_band_path(band) %></td>
        <td><%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%#= link_to 'Browse', brose_band %></td>
        <td><%= link_to "Browse", band.bn_url %>  </td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= render 'form' %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bn head:</strong>
  <%= @band.bn_head %>
</p>

<p>
  <strong>Bn url:</strong>
  <%= @band.bn_url %>
</p>

<p>
  <strong>Bn anonce:</strong>
  <%= @band.bn_anonce %>
</p>

<p>
  <strong>Bn tema:</strong>
  <%= @band.bn_tema %>
</p>

<p>
  <strong>Bn rang:</strong>
  <%= @band.bn_rang %>
</p>

<p>
  <strong>Bn coment:</strong>
  <%= @band.bn_coment %>
</p>

<%= link_to 'Edit', edit_band_path(@band) %> |
<%= link_to 'Back', bands_path %>