config/routes.rb
Rails.application.routes.draw do
  resources :tapes
  resources :bands
	root 'static_pages#home'
  match '/sets',    to: 'static_pages#sets',    via: 'get'
  match '/black',    to: 'static_pages#black',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Это подвал</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help",  help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "mySearch", root_path, class: "navbar-brand" %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Googl List <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Show List",  bands_path %></li>
                  <li><%= link_to "Update List",  new_band_path %></li>
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Економічна правда <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Show List",  tapes_path %></li>
                  <li><%= link_to "Обновить ленту",  new_tape_path %></li>
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
                
                <li><%= link_to "searchSets", sets_path %></li>
                <li><%= link_to "Help",  help_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Необходимые 3 Мета-теги всегда д.б. на первом месте -->  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap CSS -->  
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Custom styles for this template -->
    <link href="/assets/stylesheets/custom.css.scss" rel="stylesheet">

    <%#= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <title>Умный поиск></title>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
    <%= render 'layouts/header' %>

    <!-- Текст в центре экрана с заголовком  -->
      <%= yield %>
    <!-- КОНЕЦ Текст в центре экрана с заголовком  -->
      <%#= render 'layouts/footer' %>
    </div> <!-- /container -->
    <!-- jQuery первый, затем Tether, затем Bootstrap JS. -->  
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>